# NumPy
Numpy is a python library that manage lists/arrays and different mathematical operations efficiently 

In [10]:
import numpy as np

# Numpy Arrays
`np.array()` are core data structures of numpy library, numpy arrays are faster than normal lists due to C-based optimizations, important difference between `np.array()` and list is that list can have any data type while `np.array()` can only have the elements of homogeneous data types. 

In [11]:
arr=np.array([3,4,2,1])
print(arr)

[3 4 2 1]


## Different ways to define Numpy arrays
There are 6 general mechanisms for creating arrays:

1. Conversion from **other Python structures** (i.e. lists and tuples)

2. Intrinsic NumPy **array creation functions** (e.g. arange, ones, zeros, etc.)

3. **Replicating, joining, or mutating** existing arrays

4. **Reading arrays from disk**, either from standard or custom formats

5. Creating arrays from **raw bytes** through the use of **strings or buffers**

6. Use of **special library functions** (e.g., random)

[Numpy Official Article](https://numpy.org/devdocs/user/basics.creation.html#introduction)



### Conversion from other Python structures 
Using object data structures like lists, tuples, with them we can initiate a numpy array.

**Note:** The elements in the data structure must be of same data type, otherwise the statement will throw error.

In [12]:
py_list=[10,20,30,40]  # Python List
py_tuple=(50,60,70,80) # Python Tuple

demo1=np.array(py_list,dtype=float)  # np.array initialised with list and we explicitly defined the datatype of the array
demo2=np.array(py_tuple) # np.array initialised with tuple

print(f"demo1: {demo1}, {demo1.dtype}\ndemo2: {demo2}, {demo2.dtype}") #values with type of values they stored



demo1: [10. 20. 30. 40.], float64
demo2: [50 60 70 80], int64


### Intrinsic NumPy array creation functions

Using inbuilt functions like `arange()`, `ones()`, `zeros()` to initialise the array such that the array have a fixed memory space ready to use.

In [20]:
demo3=np.arange(4)         # works just like range function go from i to n-1 (i,n)
demo4=np.zeros(5)          # creates array of n size initialise values with zeros
demo5=np.ones((3,3))       # creates a matrix cus we are using (3,3) initalise values with ones      
demo6=np.empty(5)          # creates array with garbage values
demo7=np.zeros_like(demo5) # creates copy of array(demo5) but initialise it with i for (i)_like() here i=zeros

print(f"demo3 = {demo3}\ndemo4 = {demo4}\ndemo5 = {demo5}\ndemo6 = {demo6}\ndemo7 = {demo7}\n")

demo3 = [0 1 2 3]
demo4 = [0. 0. 0. 0. 0.]
demo5 = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
demo6 = [0. 0. 0. 0. 0.]
demo7 = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



**Miscellaneous:** `array.shape` is used to get the shape or dimensions of the NumPy array

In [21]:
print(f"Shape of demo5 array: {demo5.shape}") # will return (3,3)

Shape of demo5 array: (3, 3)


### Replicating, joining, or mutating existing arrays
Make array by replicating, joining or mutating existing arrays, perhaps helpful do *feature scaling* on the data set on our regression model.

In [ ]:
demo8=np.tile(demo3,3)              # Tile the array n times (array,n) and returns the replicated/mutated array
demo9=np.concatenate((demo3,demo8)) # concatenate two arrays
print(demo8)
print(demo9)

[0 1 2 3 0 1 2 3 0 1 2 3]
[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]
